FROM ubuntu:17.10
RUN apt-get update -y && apt-get install -y software-properties-common python-software-properties
RUN apt-get install -y build-essential python3.6 python3.6-venv python3-pip
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update -y && apt-get install -y default-jre

